abbr g 'git'
abbr ga 'git add'
abbr gb 'git branch'
abbr gbd 'git branch -d'
abbr gbdd 'git branch -D'
abbr gbl 'git blame'
abbr gch 'git checkout'
abbr gchb 'git checkout -b'
abbr gc 'git commit -m'
abbr gcl 'git clone'
abbr gca 'git commit --amend -m'
abbr gcp 'git cherry-pick'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gl 'git log'
abbr gm 'git merge'
abbr gp 'git push'
abbr gpf 'git push --force-with-lease'
abbr gpl 'git pull'
abbr gr 'git remote'
abbr grb 'git rebase'
abbr gs 'git status'
abbr gst 'git stash'
